[package]
name = "rust-container"
version = "0.1.0"
authors = ["Ann Guilinger"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.20.0"
rtnetlink = "0.7.0"
tokio = { version = "1", features = ["full"] }
